### ISSUE TITLE
Linux fonts

### ISSUE THREAD

**Issue by m-e-h** [mrmrs/css-system-fonts#3]
What do you think about using Liberation Sans for a more predictable look?
I've explained why it's the better option for linux here https://core.trac.wordpress.org/ticket/36753#comment:85

**Comment by mrmrs** [comment]
Thanks for the writeup and links. This looks good to me. I'll add it to the stack.

**Comment by mrmrs** [comment]
Added it to the latest version on master. Thanks for the help!
