### ISSUE TITLE
readme referencing wrong npm package & github repo

### ISSUE THREAD

**Issue by ungoldman** [mrmrs/css-system-fonts#4]
Hello! I had the idea today to create a `system-fonts` npm package and checked to see if it existed and was (not too) surprised to find that it's already been done (yay). Even better, it's doing exactly what I wanted to do (exporting a single CSS file in the `style` package.json property with a class containing an ordered laundry list of relevant system font families) (hooray). However, I noticed a couple of issues:
- the readme currently references https://www.npmjs.com/package/css-system-fonts, but seems to have been published as https://www.npmjs.com/package/system-fonts
- https://github.com/tachyons-css/css-system-fonts, also referenced in the readme, doesn't exist
- as mentioned in #2, there's a syntax error (missing comma) in the source

Not sure if you have designs on moving the repo to the `tachyons-css` org and/or merging with https://github.com/johnotander/css-system-fonts so thought I'd open an issue rather than a PR 😁

**Comment by mrmrs** [comment]
Sorry for my delay on this and thanks for the detailed write up. Super helpful. I believe everything is fixed now on master and I published to npm. Really appreciate your help. 

![giphy-7](https://cloud.githubusercontent.com/assets/1748143/18466858/5ffef1ae-7995-11e6-904c-4692cc29ca4f.gif)

**Comment by ungoldman** [comment]
yay!

![](https://media.giphy.com/media/fHiz7HAUlSaIg/giphy.gif)
